import { Montserrat, Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ProvidersTheme } from "./provider";


// Import Montserrat for titles
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "600", "700", "800", "900"],
});

// Import Inter for body text
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "400", "600"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${inter.variable} antialiased`}>
          <main className="flex flex-col justify-between h-[100vh]">
            <ProvidersTheme>
              <Navbar />
              {children}
              <Footer />
            </ProvidersTheme>
          </main>
      </body>
    </html>
  );
}
